/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as StudentsNewRouteImport } from './routes/students.new'
import { Route as StudentsIdIndexRouteImport } from './routes/students.$id.index'
import { Route as StudentsIdEditRouteImport } from './routes/students.$id.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentsRoute,
} as any)
const StudentsNewRoute = StudentsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => StudentsRoute,
} as any)
const StudentsIdIndexRoute = StudentsIdIndexRouteImport.update({
  id: '/$id/',
  path: '/$id/',
  getParentRoute: () => StudentsRoute,
} as any)
const StudentsIdEditRoute = StudentsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => StudentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/students': typeof StudentsRouteWithChildren
  '/students/new': typeof StudentsNewRoute
  '/students/': typeof StudentsIndexRoute
  '/students/$id/edit': typeof StudentsIdEditRoute
  '/students/$id/': typeof StudentsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/students/new': typeof StudentsNewRoute
  '/students': typeof StudentsIndexRoute
  '/students/$id/edit': typeof StudentsIdEditRoute
  '/students/$id': typeof StudentsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/students': typeof StudentsRouteWithChildren
  '/students/new': typeof StudentsNewRoute
  '/students/': typeof StudentsIndexRoute
  '/students/$id/edit': typeof StudentsIdEditRoute
  '/students/$id/': typeof StudentsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/students'
    | '/students/new'
    | '/students/'
    | '/students/$id/edit'
    | '/students/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/students/new' | '/students' | '/students/$id/edit' | '/students/$id'
  id:
    | '__root__'
    | '/'
    | '/students'
    | '/students/new'
    | '/students/'
    | '/students/$id/edit'
    | '/students/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StudentsRoute: typeof StudentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/students/new': {
      id: '/students/new'
      path: '/new'
      fullPath: '/students/new'
      preLoaderRoute: typeof StudentsNewRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/students/$id/': {
      id: '/students/$id/'
      path: '/$id'
      fullPath: '/students/$id/'
      preLoaderRoute: typeof StudentsIdIndexRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/students/$id/edit': {
      id: '/students/$id/edit'
      path: '/$id/edit'
      fullPath: '/students/$id/edit'
      preLoaderRoute: typeof StudentsIdEditRouteImport
      parentRoute: typeof StudentsRoute
    }
  }
}

interface StudentsRouteChildren {
  StudentsNewRoute: typeof StudentsNewRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
  StudentsIdEditRoute: typeof StudentsIdEditRoute
  StudentsIdIndexRoute: typeof StudentsIdIndexRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsNewRoute: StudentsNewRoute,
  StudentsIndexRoute: StudentsIndexRoute,
  StudentsIdEditRoute: StudentsIdEditRoute,
  StudentsIdIndexRoute: StudentsIdIndexRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StudentsRoute: StudentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
